[package]
name = "postgres-protocol"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
byteorder = "0.5"
fallible-iterator = "0.1"
hex = "0.2"
md5 = "0.2"
